### ISSUE TITLE
Erasing `extern "c" { ... }` doesn't seem to take effect. Figure out WHY

### ISSUE THREAD

**Issue by jam31118** [jam31118/pycpp#1]
I've erased `extern "c" { ... }` at 

`static PyObject *_add_add(PyObject *self, PyObject *args);`

and

`PyMODINIT_FUNC PyInit__add(void)`

respectively.

However, in both cases, the module was compiled and run with no problem.

**Comment by jam31118** [comment]
# TODO
- [x] May be the code didn't use any C++ feature. Let's test including `<iostream>` and its members such as `std::cout` and `std::endl` etc. Declare and define a function that uses these members and try to compile and run the extension module.
 - it was tested at 5f235e71bd361bbf6bcd1ac76ed8aaf54dba3b02 and the `stdout` operation with `<iostream>` seems to work well without `extern "C" { ... }`. Why?
- [x] Also, declare multiple functions with same name but with different prototypes, namely implementing overloading. See what happens during compilation and running the extension module.
 - It was tested at 03e2f5f221f55fddb54098168f16aa5470b66e9a and the overloading worked without `extern "C" { ... }`. Why is that?
- [x] May be, it's because .. the static objects such as `PyModuleDef` structure or `PyMODINIT_FUNC` object has been declared in the same source code file, rather than being in the header file. Let's try putting them in the header file.
 - It was tested at 4eda507d7b7b909e0f232a96e7f3258b9d1c15e1 and worked as well, without `extern "C" { ... }`. Why is that?

## Conclusion for a moment
From the above two tests, the `extern "C" { ... }` doesn't seems to be required. I don't know why for a moment but at least it works well so I don't need to include the `extern` expression for now.

# TODO
- [ ] Figure out why the above trials works without `extern "C" { ... }` expression.

**Comment by jam31118** [comment]
Since, the `extern "C" { ... }` doesn't seem to be needed so far, after doing some C++ features tests, this issue should be closed at least until this expression turns out to be crucial.

**Comment by jam31118** [comment]
The `extern "C"` expression seems actually take effect at 5ba1ce01193eb58c638ebef1c3366a6a7a301d58. I should figure out the difference with the above tested cases, but at least for this commit and so on I should add this `extern "C"` expression.
