### ISSUE TITLE
Build and Use library file

### ISSUE THREAD

**Issue by jam31118** [jam31118/pycpp#4]
# TO DO
- [x] Try to build library file using `distutils`
 - Implemented at f89a9bdf8242f0d71e2581b5f14e2e666b1cc9bc
- [ ] Try to use (static) library file that was built independently without using `distutils`
- [ ] Try to build and use dynamic library file if possible.

**Comment by jam31118** [comment]
# TODO
- [ ] Try build `libqprop.a` at `qprop` using `distutils`
- [ ] Try build the whole qprop with wrapper for `imag_prop`, `real_prop`, and also for `eval_tsurff` etc.
- [ ] Also, consider developing wrapper for `eval_tsurff_mpi` etc.
